spring:

  profiles:
    include: oauth

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/springbootservice
    username: sa
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

